PUT http://localhost:3003/api/blogs/67e40cbc2cc8d11e96ebc959
Content-Type: application/json

{
  "title": "Los alemanes",
  "author": "Sergio del Molino",
  "url": "https://www.amazon.es/alemanes-Premio-Alfaguara-novela-Hisp%C3%A1nica/dp/842047682X",
  "likes": 15,
  "id": "67e40cbc2cc8d11e96ebc959",
  "userId": "67ed224a54d5f5266e24e48d"
}